### ISSUE TITLE
Version 5.0 fail at launch in the flatpak container

### ISSUE THREAD

**Issue by jyvern** [zapzap-linux/zapzap#28]
**flatpak run --command=zapzap com.rtosta.zapzap --hideStart**                                    
Traceback (most recent call last):
  File "/app/bin/zapzap", line 5, in <module>
    from zapzap.__main__ import main
  File "/app/lib/python3.11/site-packages/zapzap/__main__.py", line 4, in <module>
    from zapzap.controllers.main_window import MainWindow
  File "/app/lib/python3.11/site-packages/zapzap/controllers/main_window.py", line 7, in <module>
    from zapzap.controllers.home import Home
  File "/app/lib/python3.11/site-packages/zapzap/controllers/home.py", line 5, in <module>
    from zapzap.controllers.user_container import UserContainer
  File "/app/lib/python3.11/site-packages/zapzap/controllers/user_container.py", line 5, in <module>
    from zapzap.engine.browser import Browser
  File "/app/lib/python3.11/site-packages/zapzap/engine/browser.py", line 2, in <module>
    from PyQt6.QtWebEngineWidgets import QWebEngineView
ImportError: /home/xxxx/.local/lib/python3.11/site-packages/PyQt6/Qt6/lib/libQt6Core.so.6: version `Qt_6.6' not found (required by /app/lib/python3.11/site-packages/PyQt6/QtWebEngineWidgets.abi3.so)

**Comment by jyvern** [comment]
I succeeded in running version 5.0 after building it locally as described in docs. But I've had to install  **runtime/org.kde.Sdk/x86_64/6.5** to build flatpak.

**Comment by rafatosta** [comment]
Yes. I updated the SDK, but I wouldn't need to download it manually, because when updating the SDK it would be updated too
